#!/usr/bin/env python

import sys
from optparse import OptionParser
from boto.ec2 import regions
from teaparty import CloudWatchHelper, ELBHelper, DBAdapter, Executor

# TODO: Move to library

# TODO: Unit tests

class MetricDaemon():

    cw = None
    model = None

    queue = []

    def __init__(self, region, config_filename):
        self.cw = CloudWatchHelper(region.name)
        self.elb = ELBHelper(region.name)

        self.model = DBAdapter()
        self.model.importDataFromFile(config_filename, self.elb.getLoadBalancers())

        self.createQueue()

    def __addToQueue(self, obj_type, obj_code, metric):

        dimensions = metric['dimensions']

        if obj_type == 'elb':
            dimensions.update({'LoadBalancerName': obj_code})

        elif obj_type == 'instance':
            dimensions.update({'InstanceId': obj_code})

        else:
            raise Exception('Unknown object type ' + str(obj_type))

        item = {
            'name': metric['name'],
            'uid': metric['uid'],
            'dimensions': dimensions,
            'namespace': metric['namespace'],
            'unit': metric['unit']
        }

        self.queue.append(item.copy())

    def __getNamespaces(self, dimensions):
        metrics = self.cw.getMetrics(dimensions=dimensions)
        namespaces = {}
        for metric in metrics:
            namespaces.update({str(metric.name): metric.namespace})

        return namespaces

    def __addNamespace(self, metric, namespaces):
        if metric['name'] in namespaces:
            metric['namespace'] = namespaces[metric['name']]
            return metric

        return False

    def createQueue(self):

        self.queue = []

        metrics = self.model.getMetrics()
        instances = self.model.getInstances()
        elbs = self.model.getELBs()

        for elb_uid in elbs:
            elb_name = elbs[elb_uid]['name']
            namespaces = self.__getNamespaces({'LoadBalancerName': elb_name})

            for metric_uid in elbs[elb_uid]['metrics']:
                metric = self.__addNamespace(metrics[str(metric_uid)], namespaces)
                if metric:
                    self.__addToQueue('elb', elb_name, metric)

        for instance_uid in instances:
            namespaces = self.__getNamespaces({'InstanceId': instances[instance_uid]['id']})
            for metric_uid in instances[instance_uid]['metrics']:
                metric = self.__addNamespace(metrics[str(metric_uid)], namespaces)
                if metric:
                    self.__addToQueue('instance', instances[instance_uid]['id'], metric)

    def start(self, debug=False):
        if not self.queue:
            print 'Queue is empty. Please load config first'
            return False

        # TODO: pass parameters from command line
        e = Executor(self.cw.getMetricData, self.queue, latency=2, debug=debug)
        e.execute(4)

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-r", "--region", help="Region (default ap-southeast-2)", dest="region", default="ap-southeast-2")
    parser.add_option('-d', "--debug", help='Debug web server', action='store_true')
    parser.add_option("-c", "--config", help="Configuration file (/etc/teaparty.conf by default)", dest="config", default="/etc/teaparty.conf")
    (options, args) = parser.parse_args()

    # Check region
    for r in regions():
        if r.name == options.region:
            region = r
            break
    else:
        print "Region %s not found." % options.region
        sys.exit(1)

    coyote = MetricDaemon(region, options.config)
    # coyote.start(debug=options.debug)
