#!/usr/bin/env python

import os
import sys
from optparse import OptionParser
from boto.ec2 import regions

params = {
    'socket_url': '/socket',
    'root': os.path.join(os.path.abspath(os.path.dirname(__file__)), 'teaparty/web'),
    'region': ''
}

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-r", "--region", help="Region (default ap-southeast-2)", default="ap-southeast-2")
    parser.add_option("-p", "--port", help="Port to listening (default 80)", default=80, type="int")
    parser.add_option('-d', "--debug", help='Debug web server', action='store_true')
    (options, args) = parser.parse_args()

    # Check region
    for r in regions():
        if r.name == options.region:
            params['region'] = r.name
            break
    else:
        print "Region %s not found." % options.region
        sys.exit(1)

    params['port'] = int(options.port)
    params['debug'] = options.debug

    import teaparty.server
    teaparty.server.run_dev_server()
