#!/usr/bin/env python

import sys
import imp
from optparse import OptionParser
from boto.ec2 import regions
from teaparty import CloudWatchHelper, ELBHelper, DBAdapter, Executor

# TODO: Unit tests
class MetricDaemon():

    cw = None
    elb = None
    db = None

    queue = []

    def __init__(self, region, config_filename):
        self.cw = CloudWatchHelper(region.name)
        self.elb = ELBHelper(region.name)

        self.db = DBAdapter()

        try:
            config_module = imp.load_source('config', config_filename)
        except IOError:
            print "Config file %s not found." % config_filename
            sys.exit(1)

        if config_module.config:
            self.__parseConfig(config_module.config)

        self.__createQueue()

    def __parseConfig(self, config):

        elbs = self.elb.getLoadBalancers()

        # TODO: Error handling
        for obj in config:

            # Load balancer logic
            if obj['type'] == 'elb':

                if not obj['name'] in elbs:
                    raise Exception('There is not ELB with name ' + obj['name'])

                obj['instances'] = elbs[obj['name']].instances[:]

                elb_uid = self.db.addELB(obj['name'], obj['metrics'])
                instances_uids = []

                for instance in obj['instances']:
                    instances_uids.append(self.db.addInstance(instance.id, obj['child_metrics']))

                self.db.addGroup(elb_uid, instances_uids)

    def __addToQueue(self, obj_type, obj_code, metric):

        dimensions = metric['dimensions']

        if obj_type == 'elb':
            dimensions.update({'LoadBalancerName': obj_code})

        elif obj_type == 'instance':
            dimensions.update({'InstanceId': obj_code})

        else:
            raise Exception('Unknown object type ' + str(obj_type))

        item = {
            'name': metric['name'],
            'uid': metric['uid'],
            'dimensions': dimensions,
            'namespace': metric['namespace'],
            'unit': metric['unit']
        }

        self.queue.append(item.copy())

    def __getNamespaces(self, dimensions):
        metrics = self.cw.getMetrics(dimensions=dimensions)
        namespaces = {}
        for metric in metrics:
            namespaces.update({str(metric.name): metric.namespace})

        return namespaces

    def __addNamespace(self, metric, namespaces):
        if metric['name'] in namespaces:
            metric['namespace'] = namespaces[metric['name']]
            return metric

        return False

    def __createQueue(self):

        self.queue = []

        metrics = self.db.getMetrics()
        instances = self.db.getInstances()
        elbs = self.db.getELBs()

        for elb_uid in elbs:
            elb_name = elbs[elb_uid]['name']
            namespaces = self.__getNamespaces({'LoadBalancerName': elb_name})

            for metric_uid in elbs[elb_uid]['metrics']:
                metric = self.__addNamespace(metrics[str(metric_uid)], namespaces)
                if metric:
                    self.__addToQueue('elb', elb_name, metric)

        for instance_uid in instances:
            namespaces = self.__getNamespaces({'InstanceId': instances[instance_uid]['id']})
            for metric_uid in instances[instance_uid]['metrics']:
                metric = self.__addNamespace(metrics[str(metric_uid)], namespaces)
                if metric:
                    self.__addToQueue('instance', instances[instance_uid]['id'], metric)

    def start(self, debug=False):
        if not self.queue:
            print 'Queue is empty. Please load config first'
            return False

        e = Executor(self.cw.getMetricData, self.queue, latency=2, debug=debug)
        e.execute(4)

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("-r", "--region", help="Region (default ap-southeast-2)", dest="region", default="ap-southeast-2")
    parser.add_option("-c", "--config", help="Configuration file (/etc/teaparty.conf by default)", dest="config", default="/etc/teaparty.conf")
    (options, args) = parser.parse_args()

    # Check region
    for r in regions():
        if r.name == options.region:
            region = r
            break
    else:
        print "Region %s not found." % options.region
        sys.exit(1)

    coyote = MetricDaemon(region, options.config)
    coyote.start(debug=False)